### ISSUE TITLE
 working group meeting notes github repo link not found

### ISSUE THREAD

**Issue by Susana465** [the-turing-way/bookdash#2]
I think working group notes github repo requires invite to see. I cannot see the repo. It's giving me a 404 not found.

In the README.md file "Our working group meeting notes can be found [here](https://github.com/the-turing-way/bookdash/wg-meeting-notes)"

**Comment by da5nsy** [comment]
> In the README.md file

Which readme file?

**Comment by da5nsy** [comment]
Aha, here?
https://github.com/the-turing-way/bookdash/blob/Readme-file-and-initial-set-up/README.md?plain=1#L26

**Comment by Susana465** [comment]
yes!

**Comment by da5nsy** [comment]
That link won't render currently for two reasons:
- https://github.com/the-turing-way/bookdash/pull/1 updates the readme and _also_ adds that directory (so it is currently referencing something that doesn't exist quite yet!)
- the link will need to be something like `https://github.com/the-turing-way/bookdash/tree/main/wg-meeting-notes` rather than `https://github.com/the-turing-way/bookdash/wg-meeting-notes`

**Comment by EKaroune** [comment]
@all-contributors please add @EKaroune  for doc, ideas
